### ISSUE TITLE
FunctionClauseError in Money.Ecto.Amount.Type load/1 when loading a map

### ISSUE THREAD

**Issue by A-Legg** [elixirmoney/money#135]
After updating to version 1.7 today I'm getting a function clause error while attempting to load Money types.

Versions: 
money -> 1.7.0
ecto -> 3.3.3
ecto_sql -> 3.3.4

Error: 
```
2020-03-03T04:29:08.290119+00:00 app[web.1]: ** (FunctionClauseError) no function clause matching in Money.Ecto.Amount.Type.load/1
2020-03-03T04:29:08.290120+00:00 app[web.1]: (money) lib/money/ecto/amount_type.ex:68: Money.Ecto.Amount.Type.load(%{"amount" => 882800, "currency" => "USD"})
2020-03-03T04:29:08.290121+00:00 app[web.1]: (ecto) lib/ecto/schema/loader.ex:71: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
2020-03-03T04:29:08.290121+00:00 app[web.1]: (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
2020-03-03T04:29:08.290122+00:00 app[web.1]: (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
2020-03-03T04:29:08.290123+00:00 app[web.1]: (ecto) lib/ecto/type.ex:682: Ecto.Type.load_embed/3
2020-03-03T04:29:08.290124+00:00 app[web.1]: (ecto) lib/ecto/type.ex:923: Ecto.Type.process_loaders/3
2020-03-03T04:29:08.290124+00:00 app[web.1]: (ecto) lib/ecto/repo/queryable.ex:374: Ecto.Repo.Queryable.struct_load!/6
2020-03-03T04:29:08.290132+00:00 app[web.1]: (ecto) lib/ecto/repo/queryable.ex:206: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
```

I'll go ahead and create a PR.

**Comment by Nitrino** [comment]
Hi @A-Legg 
Thanks for your feedback. Let's try to figure it out. 
What version of the library have you upgraded from? I can’t remember what this behavior would be in the `Money.Ecto.Amount.Type`.

Why do you use this type to work with stored data as a map?
For such data, we have a type `Money.Ecto.Map.Type`
https://github.com/elixirmoney/money#serialization-to-database-json-with-multiple-currency

**Comment by A-Legg** [comment]
Hey @Nitrino, thanks so much for taking the time. I really appreciate it!

> What version of the library have you upgraded from?
The upgrade was from 1.6.1 to 1.7.0.

>Why do you use this type to work with stored data as a map?
Unfortunately I don't have full context in this current project and don't know the reasoning for using 
`Money.Ecto.Map.Type`.

**Comment by Nitrino** [comment]
@A-Legg 
`Money.Ecto.Amount.Type` should be used only in cases when the project has one currency and only the amount is stored in the database.

> The upgrade was from 1.6.1 to 1.7.0.

I recheck v1.6.1 and it does not contain this behavior

**Comment by A-Legg** [comment]
@Nitrino Again, thanks so much for taking the time!

I have confirmed:
1) Our app only uses one currency and that the amounts are stored in the database as an integer.
2) Downgrading money to 1.6.1 doesn't raise this exception. 

Are you aware of any other recent changes that could produce this behavior we are seeing?

**Comment by Nitrino** [comment]
@A-Legg 
These are all the changes regarding this Ecto type in the new version.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1032291/75749070-83047e80-5d53-11ea-8a05-ee6aaf42beba.png">
This should not affect your case.
In your case, the only integer should be passed to the load from the database. 
Full diff: https://diff.hex.pm/diff/money/1.6.1..1.7.0

Could you provide code examples for reproducing this bug?
What type of data is stored in your database?

**Comment by A-Legg** [comment]
@Nitrino Unfortunately I can't share the repo but we define our types and configurations as a single currency and store then as integers.

Our config:
```
config :money,
  default_currency: :USD,
  separator: ",",
  delimeter: ".",
  symbol: "$",
  symbol_on_right: false,
  symbol_space: false,
  fractional_unit: false
```
Migration:
```  
def change do
    alter table(:vehicles) do
      add :list_price, :integer
    end
 end
```
Schema:
```
field(:list_price, Money.Ecto.Amount.Type)
```

While I am not certain this is the exact field that was raising the exception I have confirmed we don't define any of the other money data types in our codebase. If we are unable to find a solution here I can work to produce a sample project and attempt to reproduce the issues there.

As always, thanks so much for your time!
