### ISSUE TITLE
Argument error

### ISSUE THREAD

**Issue by Duveyorg** [elixirmoney/money#230]
pkg install elixir                                    No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'    Checking availability of current mirror:          [*] https://mirror.autkin.net/termux/termux-main: ok                                                Reading package lists... Done                     Building dependency tree... Done                  Reading state information... Done                 The following additional packages will be installed:
  erlang                                          The following NEW packages will be installed:
  elixir erlang                                   0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.                                      Need to get 47.2 MB of archives.                  After this operation, 134 MB of additional disk space will be used.                                 Do you want to continue? [Y/n] y
Get:1 https://mirror.autkin.net/termux/termux-main stable/main aarch64 erlang aarch64 27.0.1 [41.2 MB]                                                Get:2 https://mirror.autkin.net/termux/termux-main stable/main aarch64 elixir all 1.17.2 [5923 kB]  Fetched 47.2 MB in 28s (1696 kB/s)                Selecting previously unselected package erlang.   (Reading database ... 27278 files and directories currently installed.)
Preparing to unpack .../erlang_27.0.1_aarch64.deb ...                                               Unpacking erlang (27.0.1) ...                     Selecting previously unselected package elixir.   Preparing to unpack .../archives/elixir_1.17.2_all.deb ...                                          Unpacking elixir (1.17.2) ...                     Setting up erlang (27.0.1) ...
Setting up elixir (1.17.2) ...                     u0_a422@localhost  ~/money   master ±  mix deps.get                                            ** (ArgumentError) cannot invoke def/2 outside module                                                   (elixir 1.17.2) lib/kernel.ex:6811: Kernel.assert_module_scope/3
    (elixir 1.17.2) lib/kernel.ex:5300: Kernel.define/4                                                 (elixir 1.17.2) expanding macro: Kernel.def/2     mix.exs:94: (file)                             ✘ u0_a422@localhost  ~/money   master ± 

**Comment by Nitrino** [comment]
@Duveyorg Can you describe what you are doing? Your error doesn't seem to be library related
